version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mymail-backend
    ports:
      - "8000:80"  # Maps FastAPI to host port 8000
    depends_on:
      - mailserver
    environment:
      MAIL_SERVER: "mailserver"
      MAIL_PORT: "587"
      MAIL_USERNAME: "your_email@mymail.local"
      MAIL_PASSWORD: "your_password"
      MAIL_FROM: "your_email@mymail.local"
    restart: always

  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.mymail.local
    domainname: mymail.local
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - ./mailserver/docker-data/mail-data/:/var/mail/
      - ./mailserver/docker-data/mail-state/:/var/mail-state/
      - ./mailserver/docker-data/mail-logs/:/var/log/mail/
      - ./mailserver/docker-data/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      ENABLE_RSPAMD: "1"
      ENABLE_FAIL2BAN: "1"
      PERMIT_DOCKER: "network"
      SSL_TYPE: "manual"
      SSL_CERT_PATH: "/tmp/ssl/fullchain.pem"
      SSL_KEY_PATH: "/tmp/ssl/privkey.pem"
    cap_add:
      - NET_ADMIN
    restart: always

  frontend:
    build: ./frontend
    container_name: mymail-frontend
    ports:
      - "8080:80"
    restart: always
